# Generated by Django 3.2 on 2021-06-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'М'), ('Ж', 'Ж')], max_length=1, verbose_name='пол'),
        ),
    ]
